spring:
  application:
    name: web-kettle
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    username: test
    password: test
    url: jdbc:oracle:thin:@192.168.8.118:1521/ORCL
  freemarker:
    suffix: .html
    content-type: text/html
    template-loader-path: classpath:/templates/
    charset: UTF-8
    cache: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 4096MB
      max-request-size: 4096MB
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.webkettle.sql.entity

#统一开发平台, 认证相关
auth:
  login-path: http://localhost:8080/bpm/login.jsp
  auth-path: 192.168.8.104:8080
  system-id: 10000000010000
  test-token: __test_admin_token
#大数据相关
bigdata:
  db:
    username: gsk
    password: guoshengkai
    zookeper: 192.168.8.117:10000
    jdbcname: org.apache.hive.jdbc.HiveDriver
    jdbc-url: jdbc:hive2://${bigdata.db.zookeper}/
  hdfs:
    url: hdfs://192.168.8.117:9000
    prefix: /cust_upload/
    collection-path: /user/rms/ftp/data/
    user: gsk
    prop: hadoop/dev/
    prncipal-name: hdfsDeveloper
    keytab-path: hadoop/dev/user.keytab
    krb5-path: hadoop/dev/krb5.conf

#任务调度相关
quartz:
  prop-path: /quartz/quartz-dev.properties

logging:
  level:
    com.webkettle: INFO
  path: ./logs
  file: ./logs/big-data.log

